# CentOS8
FROM centos:8

# system update
RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y update && yum clean all

# install sudo & nano
RUN yum -y install sudo && yum install -y nano
# install ssh clients
RUN yum -y install openssh-clients

# install python3.11
RUN yum -y install openssl-devel bzip2-devel libffi-devel
RUN yum -y groupinstall "Development Tools"
RUN cd /tmp/
RUN yum -y install wget
RUN wget https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tgz \
    && tar -xzf Python-3.11.0.tgz \
    && cd Python-3.11.0 \
    && ./configure --enable-optimizations \
    && make altinstall
RUN ln -s /usr/local/bin/python3.11 /usr/bin/python3
RUN ln -s /usr/local/bin/pip3.11 /usr/bin/pip3

# install ansible
RUN python3 -m pip -V
RUN pip3 install --upgrade pip
RUN pip3 install ansible
#RUN sed -i 's|PATH=$PATH:$HOME/bin|PATH=$PATH:$HOME/bin:/root/.local/bin|g' ~/.bash_profile
#RUN source ~/.bash_profile

# COPY data
COPY ./Ansible_Playbook/ /root/Ansible_Playbook/
